version: '3.7'
services:

  api:
    build: api
    image: bhus
    ports:
      - "8000:8000"
    depends_on:
      - initdb
    environment:
      PYTHONUNBUFFERED: 1
      DB_DSN: "${DB_DSN}"
    stop_signal: SIGKILL

  initdb:
    build: initdb
    image: initdb
    volumes:
      - dataset:/dataset
    depends_on:
      - postgres
    environment:
      PYTHONUNBUFFERED: 1
      DBNAME: "${DBNAME}"
      DBPASSWORD: "${DBPASSWORD}"
      DBUSER: "${DBUSER}"
      DBHOST: "${DBHOST}"
      DBPORT: "${DBPORT}"
    stop_signal: SIGKILL
    tty: true

  postgres:
    build: postgres
    restart: always
    image: postgres:10.7
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "${DBPORT}:${DBPORT}"
    environment:
      POSTGRES_DB: "${DBNAME}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_USER: "${DBUSER}"

volumes:
  database:
  dataset:
