version: '3.7'
services:

  api:
    build: api
    image: bhus
    ports:
      - "8000:8000"
    depends_on:
      - initdb
    environment:
      PYTHONUNBUFFERED: 1
      DB_DSN: "${DB_DSN}"
    stop_signal: SIGKILL

  initdb:
    build: initdb
    image: initdb
    volumes:
      - dataset:/dataset
    depends_on:
      - postgres
    environment:
      PYTHONUNBUFFERED: 1
      DBNAME: "${DBNAME}"
      DBPASSWORD: "${DBPASSWORD}"
      DBUSER: "${DBUSER}"
      DBHOST: "${DBHOST}"
      DBPORT: "${DBPORT}"
    stop_signal: SIGKILL
    tty: true

  postgres:
    build: postgres
    restart: always
    image: postgres:10.7
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "${DBPORT}:${DBPORT}"
    environment:
      POSTGRES_DB: "${DBNAME}"
      POSTGRES_PASSWORD: "${DBPASSWORD}"
      POSTGRES_USER: "${DBUSER}"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2048M
        reservations:
          cpus: '2.0'
          memory: 1024M

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

volumes:
  database:
  dataset:
