#!/usr/bin/env python3
from utils import eprint
import db
import dataset


if __name__ == '__main__':
    eprint('maybe create tables...')
    db.create_all()
    eprint('ensuring dataset is present...')
    dataset.ensure()
    eprint('done!')
