#!/usr/bin/env python3
from aiohttp import web
import asyncio
import uvloop

from bhus import factory


if __name__ == '__main__':
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
    app = factory.make_app()
    web.run_app(app, port=8000)
